### ISSUE TITLE
Craco is still mentioned in README, although it's no longer in use :)

### ISSUE THREAD

**Issue by michaeldlfx** [dance2die/cra-template-tailwindcss-typescript#14]
<img width="1313" alt="Screenshot 2021-01-02 at 17 36 15" src="https://user-images.githubusercontent.com/24497482/103461778-372eb700-4d21-11eb-811e-21cd926d5f66.png">

**Comment by dance2die** [comment]
Thanks @michaeldlfx. I will update README :)

**Comment by dance2die** [comment]
Ok, it's updated and updated in [v2.0.1](https://www.npmjs.com/package/cra-template-tailwindcss-typescript/v/2.0.1)~

**Comment by dance2die** [comment]
@all-contributors please add @michaeldlfx for bug
