### ISSUE TITLE
"sleep" does not work on Windows

### ISSUE THREAD

**Issue by panalgin** [dance2die/cra-template-tailwindcss-typescript#19]
Hello

`"react-scripts:start": "sleep 5 && react-scripts start",` 
does not work as "sleep" is not present on win.

I'm doing 
`"react-scripts:start": "timeout /t 1 /nobreak > NUL && react-scripts start",`

wanted to point it out, maybe it's something you would like to fix

**Comment by dance2die** [comment]
TY @panalgin.

I will need to add check/command to run `sleep` on cross environment.  
As a workaround, can you try to run in PowerShell? (will try later cuz I moved to Linux).

**Comment by panalgin** [comment]
yup tried "sleep" and it works on powershell, however I am sure vscode comes with old "cmd" as the default terminal

**Comment by dance2die** [comment]
> yup tried "sleep" and it works on powershell, 

Ty for the confirmation :smile: 

> however I am sure vscode comes with old "cmd" as the default terminal

Yes. you are right. At one point of time on Windows, I changed my default shell to Posh and didn't realize the issue... :sweat: 

--- 

## Note to self

packages to try out
- [x] https://www.npmjs.com/package/system-sleep
- [x] https://www.npmjs.com/package/cli-sleep
- [x] https://github.com/sindresorhus/delay-cli

**Comment by dance2die** [comment]
I replaced `sleep` with [delay-cli](https://github.com/sindresorhus/delay-cli), @panalgin.

[v2.1.2](https://www.npmjs.com/package/cra-template-tailwindcss-typescript/v/2.1.2) has the update.

Can you check if it works on Windows as well?

**Comment by panalgin** [comment]
Yay, it is working now! Thanks a lot for the quick reaction, can I buy you a coffee? 😊

**Comment by dance2die** [comment]
yw there~ and ty for the test :smile: 

No need to buy me a coffee as you contributed to the project so

@all-contributors please add @panalgin  for bug
