### ISSUE TITLE
Dependencies not added when using NPX

### ISSUE THREAD

**Issue by quaos** [dance2die/cra-template-tailwindcss-typescript#21]
Hi.
I am trying this template out with Node + Yarn on Windows. First I run this command:
```
npx create-react-app my-tailwind-app  --template tailwindcss-typescript
```

But I found out that the generated project can't be run right away.

I ended up adding these packages, either to global or to the project's dependencies:
* npm-run-all
* delay-cli
* postcss
* postcss-cli
* autoprefixer
* typescript
* @types/react
* @types/react-dom
* @types/jest
* @testing-library/react
* @testing-library/jest-dom

Should these be described in README section for getting started?

Or better, should most of these be added to (dev) dependencies in the template from the start?

## UPDATE

After testing further, it seems to be the issue with `npx create-react-app` that does not add the dependencies to `package.json`. Using `yarn create react-app` did it as in [this comment](https://github.com/dance2die/cra-template-tailwindcss-typescript/issues/21#issuecomment-1030745388)

**Comment by dance2die** [comment]
Thank you @quaos.  
I beliee that was a problem before I had chance to update.  

--- 

I'd appreciate if you could do PR for me to review ;p 
(before I get to alot time for this).

**Comment by quaos** [comment]
> Thank you @quaos. I beliee that was a problem before I had chance to update.
> 
> I'd appreciate if you could do PR for me to review ;p (before I get to alot time for this).

Thanks.

I've re-checked the source in this repository already has these things in dependencies in `template.json`.

But somehow they didn't get into generated `package.json` when using NPX!
```
# Command: npx create-react-app test-cra-tmpl-1 --template tailwindcss-typescript
# Generated package.json:
{
  ...
  "dependencies": {
    "cra-template-tailwindcss-typescript": "2.1.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0"
  },
  ...
}
```

But Yarn can do it:
```
# Command: yarn create react-app test-cra-tmpl-2 --template tailwindcss-typescript
# Generated package.json:
{
  ...
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.15",
    "@types/react": "^17.0.39",
    "@types/react-dom": "^17.0.11",
    "autoprefixer": "10.x",
    "cross-env": "7.x",
    "delay-cli": "^1.1.0",
    "npm-run-all": "4.x",
    "postcss": "8.x",
    "postcss-cli": "8.x",
    "postcss-preset-env": "6.x",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "tailwindcss": "2.x",
    "typescript": "4.x"
  },
  ...
}
```

Both cases have all dependencies ready in `node_modules/cra-template-tailwindcss-typescript/template.json`

**Comment by dance2die** [comment]
Ty @quaos. 
What version of CRA (create-react-app) do you have?  Not sure if it's a CRA issue.  
I tried with CRA v5.x and worked for me.

And also let me update TW to version 3.x

**Comment by dance2die** [comment]
Upgraded to Tailwind CSS version 3.0. 
Could you try again @quaos?
I removed `delay` to wait for CSS generation as there is no more need for TW v3.

**Comment by quaos** [comment]
> Upgraded to Tailwind CSS version 3.0. Could you try again @quaos? I removed `delay` to wait for CSS generation as there is no more need for TW v3.

OK, now it works! Thanks!
